# -*- org -*-
* Streaming fevent/s collector

# Hi-lock: (("\\$> .*" (0 (quote hi-red-b) t)))
# Hi-lock: (("\\#> .*\\|;\\#" (0 (quote font-lock-comment-face) t)))
# Hi-lock: (("'[^']+'\\|\"[^\"]+\"" (0 (quote font-lock-string-face) t))) ;"

* TODO
** [#A] separate cdcat & scat file holders
   [[file:~/text/scfs/lib/scatfs::/from%20Cdcatfs.utils%20import%20CacheDict/][scatfs::/from *Cdcatfs*.utils import CacheDict/]]

** move Cdcatfs (Case Conflict 1)
   (that symln -> /usr/local/lib/python2.6/dist-packages/Cdcatfs)
   to other place than cdcatfs exe
   <= Dropbox rename it - is not case sensitive

** make it [[pydoc]]
** add Config
** test w/ http://ivory.idyll.org/articles/nose-intro.html#test-fixtures
   scfs> nosetests lib/ -v
   test_nose.test_uc1 ... ok
   ----------------------------------------------------------------------
   Ran 1 test in 0.004s
   OK

** [#B] 
*** @contextmanager; def [[http://groups.google.com/group/paver/browse_thread/thread/90434e3338e15796%3Fpli%3D1][pushd]](dir)


* ACT INTRO
** dev act/s file:../lib/tests/test_nose.py
*** dev env depl: (at cd ~/text/scfs/)
    >! distutil shall handle this!
    pushd /usr/lib/python2.5/site-packages/ && pakSite=`pwd` && popd
    pushd /usr/local/lib/python2.6/dist-packages && pakSite=`pwd` && popd

    >? sudo install -v -d $pakSite/Scfs/ # is necessary when vvv #> ?
    sudo ln -sv -bf `pwd`/lib/Cat*.py `pwd`/lib/Dir*.py $pakSite/Scfs/
    sudo ln -sv -bf `pwd`/lib/scatfs $pakSite/Scfs/ScatServices.py
    echo | sudo tee /usr/local/lib/python2.6/dist-packages/Scfs/__init__.py
    sudo cp -v $pakSite/Cdcatfs/utils.py $pakSite/Scfs/ #> <depends on Cdcatfs
    install -v -d /tmp/dev/scwd/a /tmp/dev/scwd/b
    PATH=$PATH:`pwd`/lib

*** TODO why scfs> find ~/mnt/cat1/WD_UC1 -ls # stops recursion??
    5    0 drwxr-xr-x   2 root     root            0 led  1  1970 /home/user/mnt/cat1/WD_UC1
    6    0 drwxr-xr-x   2 user     user           80 kvě 18 07:36 /home/user/mnt/cat1/WD_UC1/a
    7    0 drwxr-xr-x   2 user     user           60 kvě 18 07:36 /home/user/mnt/cat1/WD_UC1/b

    scfs> sudo find ~/mnt/cat1/WD_UC1/a -ls
    6    0 drwxr-xr-x   2 user     user           80 kvě 18 07:36 /home/user/mnt/cat1/WD_UC1/a
    8    0 -rw-rw-r--   1 user     user          329 kvě 18 09:05 /home/user/mnt/cat1/WD_UC1/a/123
    9    0 -rw-rw-r--   1 user     user          329 kvě 18 09:05 /home/user/mnt/cat1/WD_UC1/a/321


** longest common:
   self.__mountPoint = []
   [[file:~/text/scfs/lib/CatalogCreator.py::/for%20name%20in%20pathComponents/][for name in pathComponents]]

** <<UC1>> health-check
*** scfs> nosetests lib/ -v
    Use case 1 ... /usr/bin/find: error while loading shared libraries: libselinux.so.1: cannot read file data: Error 21
    ok
    ----------------------------------------------------------------------
    Ran 1 test in 0.426s
    OK


** <<UC2>> insert (that simplest one)
*** design: cp -r  /tmp/dev/scwd  /tmp/dev/scwd2
    python lib/scatman del WD_UC2 ~/.scfs/cat1.db
    python lib/scatman add /tmp/dev/scwd WD_UC2 ~/.scfs/cat1.db
    echo 234 > /tmp/dev/scwd/b/234
    python lib/scatman add /tmp/dev/scwd/b WD_UC2 ~/.scfs/cat1.db

*** setup
    :cleanup: rm -vr /tmp/dev/scwd/b/bb

    install -v -d /tmp/dev/scwd/b/bb /tmp/dev/scwd/b/bb/bbb
    install -v /tmp/dev/scwd/a/321 /tmp/dev/scwd/b/bb
    echo > /tmp/dev/scwd/b/bb/bbb/234

*** from Scfs.DirectoryWalker import DirectoryWalker
   for (fname,stats,fileId,parentId) in DirectoryWalker ('/tmp/dev/scwd/'):
     print fname, fileId, parentId

*** scfs$> python doc/stu/DirectoryWalker-1.py /tmp/dev/scwd/
    -argv: ['/tmp/stu.py', '/tmp/dev/scwd/a/']
    -wd: /tmp/dev/scwd/
    1 0
    b 2 1
    a 3 1
    321 4 3
    123 5 3
    123 6 2

*** scfs$> python doc/stu/DirectoryWalker-1.py /tmp/dev/scwd startAt=b/bb parentId=2 lastId=6
    -basedir: /tmp/dev/scwd
    -opts: {'lastId': 6, 'startAt': 'b/bb', 'parentId': 2}
    /tmp/dev/scwd 7 2
    b 8 7
    a 9 7
    321 10 9
    123 11 9
    123 12 8
    bb 13 8
    321 14 13
    bbb 15 13
    234 16 15

*** :tmp: scfs$> python doc/stu/DirectoryWalker-1.py /tmp/dev/scwd/a/
    -wd: /tmp/dev/scwd/a/
    1 0
    321 2 1
    123 3 1

    scfs$> python doc/stu/DirectoryWalker-1.py /tmp/dev/scwd/a/ startAt=a parentId=3 lastId=7
    -basedir: /tmp/dev/scwd/a/
    -opts: {'lastId': 7, 'startAt': 'a', 'parentId': 3}
    /tmp/dev/scwd/a 8 3
    321 9 8
    123 10 8



** insert UC/s cmp
   1. add '/tmp/dev/scwd/b' Tbl (of '/tmp/dev/scwd') [[UC2]] for new; [[UC3]] for update!
   2. add '/tmp/dev' Tbl (of '/tmp/dev/scwd') [[UC4]] » re-id Tbl root to longest common: '/tmp/dev'
     - add '/tmp/d' Tbl (of '/tmp/dev/scwd') ([[UC4]]) » re-id Tbl root to longest common: '/tmp' but inside only those 2 branches
     - add '/var/e' Tbl (of '/tmp/dev/scwd') ([[UC4]]) » re-id Tbl root to longest common: '/' :-S but inside only those 2 branches

** <<UC3>> insert -- update existing

** <<UC4>> instert of 'parent' (of existent record)
   --> re-id:
      - old root (fid '1') to '1st' free fid -- &
      - all its childs
   * (& you can do rest as UC2 ?!)


** SETUP see file:~/text/scfs-stu/doc/1st-try.emacs.con.log
   install python-pysqlite2 python-fuse cdcatfs
   usermod -a -G fuse $USER

   install -v -d ~/.scfs ~/mnt/cat1
   python lib/scatfs -d -s -o database=~/.scfs/cat1.db ~/mnt/cat1
#(<) cdcatfs -s -o database=~/.scfs/cat1.db ~/mnt/cat1

   cd ~/text/scfs; python lib/scatman add /tmp/dev/scwd WD_UC2 ~/.scfs/cat1.db
#*(<) cdcatman add doc/ CD_1 ~/.scfs/cat1.db
   ls -l ~/mnt/cat1/CD_1
   cdcatman list ~/.scfs/cat1.db
   sqlite3 ~/.scfs/cat1.db .dump

** dev tasks
*** have both cdcat & scat on 1 env; test difference/s


* STU
** TODO fuse args
   server.parser.parse_args(['-o database=/home/user/.scfs/cat1.db'])
   server.parse(values=server)

** print " -mounting to: %s" % Config.cdpoint

** from pysqlite2 import dbapi2 as sqlite
    CDLabel = 'WD_UC1'
    fileId = 6
    name = '123'
    con = sqlite.connect('/home/user/.scfs/cat1.db')
    cmd = ("SELECT fid ,pid ,fileName, st_mode, count_name, st_uid, st_gid, st_size, st_atime, st_mtime, st_ctime " +
                           "FROM %s_files " +
                           "JOIN (SELECT fileName, COUNT(fileName) AS count_name FROM %s_files WHERE fileName='%s') AS Tbl2 " +
                           "ON %s_files.fileName = Tbl2.fileName " +
    			   "WHERE fid =%d;") \
                        % (CDLabel, CDLabel, name, CDLabel, fileId)
    rows = con.cursor().execute(cmd).fetchall()
    rows

**** SELECT fid, pid, WD_UC1_files.fileName, st_nlink, Tbl2.count_name
    FROM WD_UC1_files
    JOIN (SELECT fileName, COUNT(fileName) AS count_name FROM WD_UC1_files WHERE fileName='123')
    AS Tbl2
    ON WD_UC1_files.fileName = Tbl2.fileName;


** :last: scfs> nosetests lib/ -v # <2011-05-14 Sat>
    Use case 1 ... FAIL
    ======================================================================
    FAIL: Use case 1
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/usr/lib/pymodules/python2.6/nose/case.py", line 183, in runTest
    self.test(*self.arg)
    File "/home/p-b/text/scfs/lib/tests/test_nose.py", line 48, in test_uc1
    assert f123['st_nlink'] == 2
    AssertionError: 
    -------------------- >> begin captured stdout << ---------------------
    -mounting to: ~/mnt/cat1
    -registering (blind dir) at: /tmp/scwd
    -capturing wd state: 
    <subprocess.Popen object at 0x87c9aac>
    --------------------- >> end captured stdout << ----------------------

    ----------------------------------------------------------------------
    Ran 1 test in 0.018s

    FAILED (failures=1)
    790854    4 -rw-r--r--   1 p-b      p-b             3 May 14 23:22 ./b/123
    790853    4 -rw-r--r--   1 p-b      p-b             3 May 14 23:22 ./a/321
    790852    4 -rw-r--r--   1 p-b      p-b             3 May 14 23:22 ./a/123


* DONE
** subprocess.Popen repr differs in py25 & py26 ?!
   -cleaning wd table: <subprocess.Popen object at 0xb7aceb8c>
   -> DONE by pop = subprocess.Popen(shlex.split(cmd), stdout=subprocess.PIPE)
    print " -cleaning wd table: %s" % pop.communicate() ...

** i got 2 traceback/s in 1 tc, <2011-05-18 St>
   -> DONE by expanduser on Config.db
   <= it is from cdcatman xy subprocess/es

*** 2nd one:
   Traceback (most recent call last):
   ----------------------------------------------------------------------
   File "/usr/bin/cdcatman", line 87, in <module>
   catCreator = CatalogCreator(dbFile, mountPoint, CDLabel)
   File "/usr/lib/python2.5/site-packages/Cdcatfs/CatalogCreator.py", line 32, in __init__
   self.__initDb();
   File "/usr/lib/python2.5/site-packages/Cdcatfs/CatalogCreator.py", line 60, in __initDb
   con = sqlite.connect(self.__dbFile)
   pysqlite2.dbapi2.OperationalError: unable to open database file



* FORM/s
** .desktop
   (setq ibuffer-filter-groups
   '(("scfs|.py"
   (or
   (filename . "scfs\\|\\.py")))
   ("dev|catfs stu"
   (or
   (filename . "dev\\|catfs")))
   ("^*"
   (name . "^*"))))
