# -*- org -*-
* Streaming fevent/s collector

* TODO
** [#A] separate cdcat & scat file holders
** move Cdcatfs (Case Conflict 1)
   (that symln -> /usr/local/lib/python2.6/dist-packages/Cdcatfs)
   to other place than cdcatfs exe
   <= Dropbox rename it - is not case sensitive

** make it [[pydoc]]
** add Config
** test w/ http://ivory.idyll.org/articles/nose-intro.html#test-fixtures
   scfs> nosetests lib/ -v
   test_nose.test_uc1 ... ok
   ----------------------------------------------------------------------
   Ran 1 test in 0.004s
   OK

** [#B] 
*** @contextmanager; def [[http://groups.google.com/group/paver/browse_thread/thread/90434e3338e15796%3Fpli%3D1][pushd]](dir)


* ACT INTRO
** dev file:../lib/tests/test_nose.py
*** dev env depl: 
    install -v -d /tmp/dev/scwd/a /tmp/dev/scwd/b
    PATH=$PATH:`pwd`/lib

*** from pysqlite2 import dbapi2 as sqlite
    CDLabel = 'WD_UC1'
    fileId = 6
    name = '123'
    con = sqlite.connect('/home/user/.scfs/cat1.db')
    cmd = ("SELECT fid ,pid ,fileName, st_mode, count_name, st_uid, st_gid, st_size, st_atime, st_mtime, st_ctime " +
                           "FROM %s_files " +
                           "JOIN (SELECT fileName, COUNT(fileName) AS count_name FROM %s_files WHERE fileName='%s') AS Tbl2 " +
                           "ON %s_files.fileName = Tbl2.fileName " +
    			   "WHERE fid =%d;") \
                        % (CDLabel, CDLabel, name, CDLabel, fileId)
    rows = con.cursor().execute(cmd).fetchall()
    rows

**** SELECT fid, pid, WD_UC1_files.fileName, st_nlink, Tbl2.count_name
    FROM WD_UC1_files
    JOIN (SELECT fileName, COUNT(fileName) AS count_name FROM WD_UC1_files WHERE fileName='123')
    AS Tbl2
    ON WD_UC1_files.fileName = Tbl2.fileName;

*** TODO why scfs> sudo find ~/mnt/cat1/WD_UC1 -ls # stops recursion??
    5    0 drwxr-xr-x   2 root     root            0 led  1  1970 /home/user/mnt/cat1/WD_UC1
    6    0 drwxr-xr-x   2 user     user           80 kvě 18 07:36 /home/user/mnt/cat1/WD_UC1/a
    7    0 drwxr-xr-x   2 user     user           60 kvě 18 07:36 /home/user/mnt/cat1/WD_UC1/b

    scfs> sudo find ~/mnt/cat1/WD_UC1/a -ls
    6    0 drwxr-xr-x   2 user     user           80 kvě 18 07:36 /home/user/mnt/cat1/WD_UC1/a
    8    0 -rw-rw-r--   1 user     user          329 kvě 18 09:05 /home/user/mnt/cat1/WD_UC1/a/123
    9    0 -rw-rw-r--   1 user     user          329 kvě 18 09:05 /home/user/mnt/cat1/WD_UC1/a/321

*** DONE :last: scfs> nosetests lib/ -v # <2011-05-14 Sat>
    Use case 1 ... FAIL
    ======================================================================
    FAIL: Use case 1
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/usr/lib/pymodules/python2.6/nose/case.py", line 183, in runTest
    self.test(*self.arg)
    File "/home/p-b/text/scfs/lib/tests/test_nose.py", line 48, in test_uc1
    assert f123['st_nlink'] == 2
    AssertionError: 
    -------------------- >> begin captured stdout << ---------------------
    -mounting to: ~/mnt/cat1
    -registering (blind dir) at: /tmp/scwd
    -capturing wd state: 
    <subprocess.Popen object at 0x87c9aac>
    --------------------- >> end captured stdout << ----------------------

    ----------------------------------------------------------------------
    Ran 1 test in 0.018s

    FAILED (failures=1)
    790854    4 -rw-r--r--   1 p-b      p-b             3 May 14 23:22 ./b/123
    790853    4 -rw-r--r--   1 p-b      p-b             3 May 14 23:22 ./a/321
    790852    4 -rw-r--r--   1 p-b      p-b             3 May 14 23:22 ./a/123


** SETUP see file:~/text/scfs-stu/doc/1st-try.emacs.con.log
   install python-pysqlite2 python-fuse cdcatfs
   usermod -a -G fuse $USER

   install -v -d ~/.scfs ~/mnt/cat1
   python lib/scatfs -d -s -o database=~/.scfs/cat1.db ~/mnt/cat1
#(<) cdcatfs -s -o database=~/.scfs/cat1.db ~/mnt/cat1

   cd ~/text/scfs; cdcatman add doc/ CD_1 ~/.scfs/cat1.db
   ls -l ~/mnt/cat1/CD_1
   cdcatman list ~/.scfs/cat1.db
   sqlite3 ~/.scfs/cat1.db .dump

** dev tasks
*** have both cdcat & scat on 1 env; test difference/s

* STU
** print " -mounting to: %s" % Config.cdpoint


* DONE
** subprocess.Popen repr differs in py25 & py26 ?!
   -cleaning wd table: <subprocess.Popen object at 0xb7aceb8c>
   -> DONE by pop = subprocess.Popen(shlex.split(cmd), stdout=subprocess.PIPE)
    print " -cleaning wd table: %s" % pop.communicate() ...

** i got 2 traceback/s in 1 tc, <2011-05-18 St>
   -> DONE by expanduser on Config.db
   <= it is from cdcatman xy subprocess/es

*** 2nd one:
   Traceback (most recent call last):
   ----------------------------------------------------------------------
   File "/usr/bin/cdcatman", line 87, in <module>
   catCreator = CatalogCreator(dbFile, mountPoint, CDLabel)
   File "/usr/lib/python2.5/site-packages/Cdcatfs/CatalogCreator.py", line 32, in __init__
   self.__initDb();
   File "/usr/lib/python2.5/site-packages/Cdcatfs/CatalogCreator.py", line 60, in __initDb
   con = sqlite.connect(self.__dbFile)
   pysqlite2.dbapi2.OperationalError: unable to open database file



* FORM/s
** .desktop
   (setq ibuffer-filter-groups
   '(("scfs|.py"
   (or
   (filename . "scfs\\|\\.py")))
   ("dev|catfs stu"
   (or
   (filename . "dev\\|catfs")))
   ("^*"
   (name . "^*"))))
